In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
df = pd.read_csv('Desktop/HR.csv')

In [4]:
df.head()

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [5]:
amh_s = df["average_monthly_hours"]

In [6]:
amh_s.value_counts()

156    153
135    153
149    148
151    147
160    136
145    134
140    129
158    127
143    127
257    126
157    126
155    125
260    124
245    124
148    123
153    122
137    122
154    121
159    121
139    120
147    118
141    115
255    115
134    114
254    113
243    112
142    112
224    112
152    112
264    111
      ... 
291     17
309     16
101     16
294     16
114     15
290     15
292     15
307     14
97      14
115     14
124     13
293     13
298     13
295     12
110     12
118     12
300     11
99      11
122     11
119     10
116     10
120     10
112     10
107     10
302      8
297      7
303      6
288      6
299      6
96       6
Name: average_monthly_hours, Length: 215, dtype: int64

In [7]:
amh_s.mean()

201.0417277696307

In [8]:
amh_s.std()

49.94181527437911

In [9]:
amh_s.max()

310

In [10]:
amh_s.min()

96

In [11]:
amh_s.skew()

0.05322458779916304

In [12]:
amh_s.kurt()

-1.1350158577565719

In [13]:
amh_s = amh_s[amh_s<amh_s.quantile(0.75)+1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))]
[amh_s>amh_s.quantile(0.25)-1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))]

[0        True
 1        True
 2        True
 3        True
 4        True
 5        True
 6        True
 7        True
 8        True
 9        True
 10       True
 11       True
 12       True
 13       True
 14       True
 15       True
 16       True
 17       True
 18       True
 19       True
 20       True
 21       True
 22       True
 23       True
 24       True
 25       True
 26       True
 27       True
 28       True
 29       True
          ... 
 14972    True
 14973    True
 14974    True
 14975    True
 14976    True
 14977    True
 14978    True
 14979    True
 14980    True
 14981    True
 14982    True
 14983    True
 14984    True
 14985    True
 14986    True
 14987    True
 14988    True
 14989    True
 14990    True
 14991    True
 14992    True
 14993    True
 14994    True
 14995    True
 14996    True
 14997    True
 14998    True
 14999    True
 15000    True
 15001    True
 Name: average_monthly_hours, Length: 15002, dtype: bool]

In [14]:
len(amh_s)

15002

In [15]:
np.histogram(amh_s.values,bins=10)

(array([ 367, 1240, 2736, 1722, 1628, 1712, 1906, 2240, 1127,  324]),
 array([ 96. , 117.4, 138.8, 160.2, 181.6, 203. , 224.4, 245.8, 267.2,
        288.6, 310. ]))

In [16]:
np.histogram(amh_s.values, bins=np.arange(amh_s.min(),amh_s.max() + 10,10))

(array([ 168,  171,  147,  807, 1153, 1234, 1075,  824,  818,  758,  751,
         738,  856,  824,  987, 1002, 1045,  935,  299,  193,  131,   86]),
 array([ 96, 106, 116, 126, 136, 146, 156, 166, 176, 186, 196, 206, 216,
        226, 236, 246, 256, 266, 276, 286, 296, 306, 316]))