In [2]:
import numpy as np

# 1. array 基本信息以及生成各种常见array基本操作

#### 生成array, 得到对应的基本信息

In [6]:
array = np.array([[1,2,3],[2,3,4]])
array

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
array.dtype  #每个元素的类型

dtype('int64')

In [9]:
array.ndim  #array的维度

2

In [11]:
array.shape  # 形状 两行三列

(2, 3)

In [13]:
array.size  # array的大小 == array中所有元素的个数

6

#### array 的 dtype设置

In [14]:
a = np.array([2,23,4], dtype=np.float32)

In [15]:
a


array([ 2., 23.,  4.], dtype=float32)

In [16]:
a.dtype

dtype('float32')

In [17]:
aa = np.array([2,3,4,6], dtype=np.int)

In [18]:
aa.dtype

dtype('int64')

#### 生成常见array格式

In [19]:
a1 = np.zeros((2,3), dtype=int) # 生成shape=(2,3)的全为0的array

In [20]:
a1

array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
a2 = np.ones((2,3), dtype = int) # 生成shape=(2,3)全为1的array

In [22]:
a2

array([[1, 1, 1],
       [1, 1, 1]])

In [3]:
a4 = np.arange(10,20,2) #生成array 10 到 20 每隔2增加, for循环中主要使用
a4

array([10, 12, 14, 16, 18])

In [4]:
a5 = np.arange(12) # 生成array 0到12-1=11, 每一个增加, for 循环中非常常用
a5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
a6 = np.arange(12).reshape((3,4)) # 这里主要展示 reshape 的功能, 能够重新定义矩阵的形状
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a7 = np.linspace(1,10,4).reshape((2,2)) # 1 和 10 之间4个元素越过, 这个主要应用在插值运算或者matplotlib画光滑曲线的时候计算用到
a7

array([[ 1.,  4.],
       [ 7., 10.]])

# 2. array之间的计算

In [10]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [13]:
b = np.arange(4)
b 

array([0, 1, 2, 3])

In [14]:
c = a + b
c

array([10, 21, 32, 43])

In [15]:
c1 = a - b
c1

array([10, 19, 28, 37])

In [16]:
aa = np.array([[1,2,3,4],
              [11,22,33,44]])
aa

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [17]:
bb = np.arange(4)
bb

array([0, 1, 2, 3])

In [18]:
dd = aa + bb

In [19]:
dd

array([[ 1,  3,  5,  7],
       [11, 23, 35, 47]])

In [20]:
# 如果是不同维度的array进行加减法的话，程序就是把维度低的array自动复制扩展到大维度的array,
# 进行相加当然前提条件是两个不同维度的array进行相加的时候，
# 低维度的array的shape也要和高维度的array其中一个shape相同，例如上面代码所示，(2,4) (1,4) 都有个shape为４

#### 乘除法

In [25]:
d = np.array([[1,2],
             [3,4]])
print(d)
e = np.arange(1,8,2).reshape((2,2))
e

[[1 2]
 [3 4]]


array([[1, 3],
       [5, 7]])

In [23]:
d * e

array([[ 1,  6],
       [15, 28]])

In [26]:
d / e

array([[1.        , 0.66666667],
       [0.6       , 0.57142857]])

#### 平方，三角函数，比较元素大小

In [28]:
a = np.array([10,20,30,40])
print(a)

b = np.arange(4)

print(b)

[10 20 30 40]
[0 1 2 3]


In [30]:
c3 = 10 * np.sin(a) # sin函数
c3

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [31]:
b < 3

array([ True,  True,  True, False])

In [32]:
b == 3

array([False, False, False,  True])

#### 矩阵相乘

In [35]:
d = np.array([[1,2],
             [3,4]])
print(d)
print('-----------')
e = np.arange(1,8,2).reshape((2,2))
print(e)

[[1 2]
 [3 4]]
-----------
[[1 3]
 [5 7]]


In [36]:
np.dot(d,e)

array([[11, 17],
       [23, 37]])

In [37]:
d.dot(e)  # np.dot(d, e) 与d.dot(e)一样，都为d和e进行矩阵相乘

array([[11, 17],
       [23, 37]])

#### 随机数和max,min,sum

In [38]:
f = np.random.random((2,4))

In [39]:
f

array([[0.92660148, 0.04600289, 0.63578928, 0.1234634 ],
       [0.79702269, 0.49518051, 0.06295508, 0.63369082]])

In [40]:
np.sum(f)

3.7207061475766716

In [41]:
np.min(f)

0.04600288560115129

In [42]:
np.max(f)

0.9266014792140934

In [43]:
np.sum(f, axis=0)

array([1.72362417, 0.5411834 , 0.69874436, 0.75715422])

In [49]:
np.sum(f, axis=1)

array([1.73185705, 1.9888491 ])

In [47]:
np.min(f, axis=1)

array([0.04600289, 0.06295508])

In [48]:
np.max(f, axis=0)

array([0.92660148, 0.49518051, 0.63578928, 0.63369082])

In [53]:
# 顾名思义，sum为总，min为最小，max为最大，如果不设置axis维度参数的话，则都为整个array的元素来说，
# 但一般我们运用都只是算某个维度的sum,max,min，在二维数据中，axis=0代表行，第一个维度，
# axis=1，代表列为第二个维度，其实这么记并不是很好很有可能记错，我一般都是这么记得：axis=0为行，
# 那意思就是每一行都要算呗？算完那不就是一列的每一行算个数被，axis=1类推，多维数据类推即可

#### 矩阵转置和排序，以及元素比较大小重置元素方法

In [54]:
c = np.arange(14,2,-1).reshape((3,4))
c

array([[14, 13, 12, 11],
       [10,  9,  8,  7],
       [ 6,  5,  4,  3]])

In [55]:
np.sort(c) # 每一行进行重新大小排序当然也有axis参数配置，根据我的axis参数说明来操作

array([[11, 12, 13, 14],
       [ 7,  8,  9, 10],
       [ 3,  4,  5,  6]])

In [56]:
np.transpose(c) # 转置　同下面操作 同c.T

array([[14, 10,  6],
       [13,  9,  5],
       [12,  8,  4],
       [11,  7,  3]])

In [57]:
c.T

array([[14, 10,  6],
       [13,  9,  5],
       [12,  8,  4],
       [11,  7,  3]])

In [58]:
np.clip(c, 5, 9) # c矩阵中的元素小于５的等于５，大于９的等于９

array([[9, 9, 9, 9],
       [9, 9, 8, 7],
       [6, 5, 5, 5]])

#### 平均值、中值，累加，后减前

In [70]:
a = np.arange(2,14).reshape((3,4))
print(a)
np.cumsum(a)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90])

In [62]:
np.average(a) # 平均值

7.5

In [64]:
np.median(a) # 中值

7.5

In [66]:
np.diff(a) # 当前元素减去前面元素的差

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [68]:
np.cumsum(a) #每个元素变成当前元素＋前面所有元素的和

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90])

In [72]:
np.cumsum(a, axis = 0) 

array([[ 2,  3,  4,  5],
       [ 8, 10, 12, 14],
       [18, 21, 24, 27]])

# 3. 索引

#### 最大值最小值索引，非零索引

In [74]:
a = np.array([[2,6,0, 4],
             [4,8,9,1],
             [10,2,3,11]])
a

array([[ 2,  6,  0,  4],
       [ 4,  8,  9,  1],
       [10,  2,  3, 11]])

In [76]:
np.argmin(a)  # 最小值的索引 0 index 2

2

In [78]:
np.argmax(a)  # 最大值的索引 12 index 11

11

In [79]:
np.argmin(a, axis=0) # 

array([0, 2, 0, 1])

In [81]:
np.argmin(a, axis=1)

array([2, 3, 1])

In [82]:
np.nonzero(a)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([0, 1, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

#### 取值，取列或行 

In [83]:
a = np.arange(3,15).reshape((3,4))
a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [86]:
a[1] # 索引为1的行，

array([ 7,  8,  9, 10])

In [87]:
a[:][1]

array([ 7,  8,  9, 10])

In [88]:
a[2][1]

12

In [89]:
a[2,1]

12

In [91]:
a[:,1] # 索引为１的列,生成为行向量

array([ 4,  8, 12])

In [94]:
a[:, 1:2] # 索引为１的列，生成为列向量

array([[ 4],
       [ 8],
       [12]])

In [95]:
a[:, 1:3]

array([[ 4,  5],
       [ 8,  9],
       [12, 13]])

#### 迭代元素和降维

In [96]:
a = np.arange(3, 15).reshape((3,4))

In [97]:
a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [100]:
# 取每一行迭代
for row in a: 
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [101]:
# 取每列  翻转数组
for column in a.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [103]:
a.flatten() # 组合成一行

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [104]:
b.flatten()

array([0, 1, 2, 3])

In [106]:
for item in a.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


# 4. 合并与分开

#### 两个合并、多个合并（行向量转换成列向量）

In [112]:
a = np.array([1,1,2])
b = np.array([2,3,4])
c = np.vstack((a,b))
#d.hstack((a,b))

In [108]:
c

array([[1, 1, 2],
       [2, 3, 4]])