In [83]:
import numpy as np

# [NumPy 中文文档](https://www.numpy.org.cn/article/basics/understanding_numpy.html/)

In [5]:
my_array = np.array([1, 2, 3, 4, 5])

In [6]:
my_array


array([1, 2, 3, 4, 5])

In [7]:
my_array.shape


(5,)

In [8]:
my_array[1]

2

In [9]:
my_array[1] = 3

In [10]:
my_array

array([1, 3, 3, 4, 5])

In [11]:
zeroArr = np.zeros((5))

In [12]:
zeroArr

array([0., 0., 0., 0., 0.])

In [13]:
random_array = np.random.random((5))
random_array

array([0.20218779, 0.60413735, 0.08533378, 0.88716795, 0.89518485])

In [14]:
my_2d_arr = np.zeros((2,3))
my_2d_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
my_we = np.ones((2,4))

In [16]:
my_we

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
my_we[1][3]

1.0

In [18]:
my_d = np.array([[4,5], [6,1]])
my_d

array([[4, 5],
       [6, 1]])

In [19]:
my_d[0, 1]

5

In [20]:
my_d.shape


(2, 2)

In [21]:
my_d[:,1]

array([5, 1])

In [22]:
my_d[0,:]

array([4, 5])

In [23]:
my_d[1,:]

array([6, 1])

In [24]:
my_d[:,0]

array([4, 6])

In [25]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.0, 6.0], [7.0,8.0]])

In [26]:

sum = a + b
sum

array([[ 6.,  8.],
       [10., 12.]])

In [27]:
a

array([[1., 2.],
       [3., 4.]])

In [28]:
b

array([[5., 6.],
       [7., 8.]])

In [29]:
difference = a - b
difference

array([[-4., -4.],
       [-4., -4.]])

In [30]:
product = a * b
product

array([[ 5., 12.],
       [21., 32.]])

In [31]:
quotient = a / b

In [32]:
quotient

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [33]:
ma = a.dot(b)
ma

array([[19., 22.],
       [43., 50.]])

In [34]:
aa = np.array([0,1,2,3,4,5])
aa
aa[3]

3

In [35]:
bb = np.array((0,1,2,3,4,5))
bb

array([0, 1, 2, 3, 4, 5])

In [36]:
cc = np.arange(5)
cc

array([0, 1, 2, 3, 4])

In [37]:
dd = np.linspace(0, 2*np.pi, 5)
dd

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [38]:
ab = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])

In [39]:
ab[0,1:4]

array([12, 13, 14])

In [40]:
ab[1:4, 0]

array([16, 21, 26])

In [41]:
ab[::2,::2]

array([[11, 13, 15],
       [21, 23, 25],
       [31, 33, 35]])

In [42]:
dc = np.arange(10)
dc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [49]:
ddc = np.full((3,3), True, dtype=bool)
ddc


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [50]:
ddc.ndim


2

In [52]:
ddc.shape

(3, 3)

In [45]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 ==1]

array([1, 3, 5, 7, 9])

In [46]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [48]:
arr.ndim

1

In [51]:
arr.shape

(10,)

In [53]:
ddc.size

9

In [54]:
arr.size

10

In [55]:
ddc.dtype

dtype('bool')

In [56]:
arr.dtype


dtype('int64')

In [57]:
arr.itemsize

8

In [58]:
ddc.itemsize

1

In [59]:
ddc.data

In [60]:
arr.data

In [61]:
a = np.arange(15).reshape(3,5)

In [62]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
a = np.array([20,30,40,50])
a

array([20, 30, 40, 50])

In [65]:
b = np.array(4)
b

array(4)

In [66]:
c = a - b
c

array([16, 26, 36, 46])

In [69]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(out)
out

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [80]:
arr = np.arange(10)

cc =arr.reshape(2, 5)
print(arr)
cc

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
arr = np.arange(10)
arr.reshape(2, -1) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [85]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,4])
np.intersect1d(a,b)

array([2, 4])

In [87]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])